### PR TITLE
Make A record regexp more robust

### LINKED ISSUE #31: Uncaught Error: Missing A record
Many IGC files from multiple instruments/software are throwing 
```
Uncaught Error: Missing A record
```
and failing parsing, even with lenient mode.

Example files:
https://www.xcontest.org/hungary/repulesek/reszletei:donath/26.06.2018/09:23
https://www.xcontest.org/hungary/repulesek/reszletei:lorta/26.06.2018/09:36

### PR DESCRIPTION
**Pull request by vicb**
Take 2 on this.

As you suggested in my previous PR, the regexp was wrong. This PR should fix this.

fixes #31 
closes #126

### CODE REVIEW

**Comment by vicb** [comment]
@Turbo87 Do you think this is mergeable ? If so could you publish a npm release with it ?
Thanks

**Comment by vicb** [comment]
ping ?

**Comment by Turbo87** [comment]
sorry, been a busy few days. it's still on my todo list... 😞

**Comment by vicb** [comment]
No problem.
I added tests with A record I found in the wild.
Thanks for taking care of this when you have time.

**Comment by vicb** [comment]
@Turbo87 no pressure but do you have an ETA for merging this PR ? (otherwise I'll point to my own branch). Thanks.

**Comment by vicb** [comment]
ping ?

File: test.ts [hunk 1]
```diff
@@ -158,6 +158,20 @@ describe('IGCParser', () => {
       additionalData: null,
     });
 
+    test.pass('AXCT XCTrack 0.6.0 on samsung GT-S6500 2.3.6', {
+      manufacturer: 'XCT',
+      loggerId: ' XCTrack 0.6.0 on samsung GT-S6500 2.3.6',
```
Comment (Turbo87) [inline test.ts]: I think I would prefer it if this string was in `additionalData` instead of the `loggerId` 🤔 

The `loggerId` field has a defined format and this is certainly not complying with that format.

Can you check if adjusting the regex with `(?:FLIGHT:(\d+)|\:(.+)| (.+))` solves the issue?

Comment (vicb) [reply test.ts]: According to the spec:

> A MMM NNN: TEXT STRING CR LF
> The FR Serial ID, valid characters alphanumeric. For IGC FRs this must be three alphanumeric characters. Non-IGC FRs may use different systems. 

Additional would appear after `:` so I guess we are in the "Non-IGC FRs may use different systems." here ?

What do you think ?

Comment (Turbo87) [reply test.ts]: maybe, but "XCTrack 0.6.0 on samsung GT-S6500 2.3.6" doesn't look like a `loggerId` to me. it looks more like a version string IMHO.

Comment (vicb) [reply test.ts]: I chose to populate `loggerId` because:
1. It seems to be compliant with the spec (as quoted in my previous message),
2. There must be a `loggerId` for the result to be valid, see https://github.com/Turbo87/igc-parser/blob/master/index.ts#L181-L183

Also I have found the following A record generated by a Syride, SYS'Nav: `AXSR`

So open questions are:
1. Should we move non-standard ids to `additionalData` ?
2. Should we check the manufacturer instead of the `loggerId` for the A field as you mentioned in the other PR ?

Comment (Turbo87) [reply test.ts]: > Should we check the manufacturer instead of the loggerId for the A field as you mentioned in the other PR ?

yes, I think that makes sense

> Should we move non-standard ids to additionalData ?

👍

File: index.ts [hunk 2]
```diff
@@ -270,13 +270,18 @@ class IGCParser {
   private parseARecord(line: string): IGCParser.ARecord {
     let match = line.match(RE_A);
     if (!match) {
+      if (line.match(/^A\w{3}/)) {
+        const manufacturer = lookupManufacturer(line.substr(1, 3));
+        const additionalData = line.length > 4 ? line.substr(4) : null;
+        return { manufacturer, additionalData, numFlight: null, loggerId: '' };
```
Comment (vicb) [inline index.ts]: `loggerId` is `""` instead of null so that `IGCParser.ARecord` does not have to be modified (backward compatibility)

**Comment by vicb** [comment]
@Turbo87 I have just updated the PR with what we last discussed.

**Comment by vicb** [comment]
:+1:
